import { readFile, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, URL } from 'node:url';
import { execFileSync } from 'node:child_process';
import { compile } from 'json-schema-to-typescript';
import Ajv from 'ajv';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { build } from 'esbuild';
import { format } from 'prettier';

const root = fileURLToPath(new URL('../', import.meta.url));
const workspace = join(root, '../..');
const check = process.argv.includes('--check');
const schemaText = await readFile(join(root, 'schemas/protocol.schema.json'), 'utf8');
const schema = JSON.parse(schemaText);
const names = schema.oneOf.map(({ $ref }) => $ref.split('/').at(-1));
const style = JSON.parse(await readFile(join(workspace, '.prettierrc.json'), 'utf8'));
const banner = '/* Generated by pnpm protocol:generate. Do not edit. */';
const outputs = new Map();

outputs.set(
  'src/generated/types.ts',
  await compile(schema, 'WireMessage', {
    bannerComment: banner,
    unreachableDefinitions: true,
    additionalProperties: false,
    // Keep bounded arrays readable; runtime validators enforce length limits.
    maxItems: 4,
    style,
  })
);

const ajv = new Ajv({
  strict: true,
  allErrors: false,
  ownProperties: true,
  inlineRefs: false,
  code: { source: true, esm: true },
});
ajv.addSchema(schema);
const validators = Object.fromEntries(
  names.map((name) => [name, `${schema.$id}#/definitions/${name}`])
);
const standalone = standaloneCode(ajv, validators);
// Bundle Ajv's small runtime helpers at generation time. Shipping Ajv.compile
// would require eval/new Function, which MV3 disallows.
const bundled = await build({
  absWorkingDir: root,
  stdin: { contents: standalone, resolveDir: root, sourcefile: 'validators.js' },
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  write: false,
});
outputs.set('src/generated/validators.js', `${banner}\n${bundled.outputFiles[0].text}`);
outputs.set(
  'src/generated/messages.ts',
  `${banner}\nimport type * as Types from './types.js';\n` +
    `export interface MessageMap {\n${names.map((n) => `  ${n}: Types.${n};`).join('\n')}\n}\n` +
    `export const MESSAGE_NAMES = ${JSON.stringify(names)} as const;\n` +
    `export const PROTOCOL_VERSION = ${JSON.stringify(schema.definitions.ProtocolVersion.const)} as const;\n`
);
outputs.set('python/privacagent_protocol/_schema.json', schemaText);
outputs.set(
  'python/privacagent_protocol/_registry.py',
  '# Generated by pnpm protocol:generate. Do not edit.\nfrom . import models\n\n' +
    `PROTOCOL_VERSION = ${JSON.stringify(schema.definitions.ProtocolVersion.const)}\n` +
    `MESSAGE_MODELS = {\n${names.map((n) => `    "${n}": models.${n},`).join('\n')}\n}\n`
);
outputs.set(
  'python/privacagent_protocol/__init__.pyi',
  '# Generated by pnpm protocol:generate. Do not edit.\n' +
    'from typing import Any, Literal, overload\nfrom pydantic import BaseModel\nfrom . import models as models\n\n' +
    `PROTOCOL_VERSION: Literal[${JSON.stringify(schema.definitions.ProtocolVersion.const)}]\n` +
    'MESSAGE_NAMES: tuple[str, ...]\n' +
    'class ProtocolValidationError(ValueError): ...\n' +
    'def get_schema(name: str) -> dict[str, Any]: ...\n' +
    'def is_message(name: str, value: Any) -> bool: ...\n\n' +
    names
      .map(
        (name) =>
          `@overload\ndef parse_message(name: Literal["${name}"], value: Any) -> models.${name}: ...\n`
      )
      .join('\n') +
    '\n@overload\ndef parse_message(name: str, value: Any) -> BaseModel: ...\n'
);

const temp = await mkdtemp(join(tmpdir(), 'privacagent-codegen-'));
try {
  const output = join(temp, 'models.py');
  execFileSync(
    'uv',
    [
      'run',
      '--locked',
      '--project',
      workspace,
      'datamodel-codegen',
      '--input',
      join(root, 'schemas/protocol.schema.json'),
      '--input-file-type',
      'jsonschema',
      '--output',
      output,
      '--output-model-type',
      'pydantic_v2.BaseModel',
      '--target-python-version',
      '3.12',
      '--disable-timestamp',
      '--use-standard-collections',
      '--use-union-operator',
      '--enum-field-as-literal',
      'all',
      '--field-constraints',
      '--use-annotated',
      '--strict-types',
      'str',
      'float',
      'bool',
      '--extra-fields',
      'forbid',
      '--strict-nullable',
      '--use-schema-description',
      '--formatters',
      'black',
      'isort',
    ],
    { cwd: workspace, stdio: 'inherit' }
  );
  outputs.set('python/privacagent_protocol/models.py', await readFile(output, 'utf8'));
} finally {
  await rm(temp, { recursive: true, force: true });
}

let stale = false;
for (const [path, raw] of outputs) {
  const contents = /\.(ts|js|json)$/.test(path)
    ? await format(raw, { ...style, parser: path.endsWith('.json') ? 'json' : 'typescript' })
    : raw;
  const target = join(root, path);
  if (check) {
    const existing = await readFile(target, 'utf8').catch(() => null);
    if (existing !== contents) {
      console.error(`Stale generated file: ${path}`);
      stale = true;
    }
  } else {
    await writeFile(target, contents);
  }
}
if (stale) process.exitCode = 1;
else
  console.log(
    check ? 'Protocol generated files are current.' : 'Protocol generated files updated.'
  );
