# Generated by pnpm protocol:generate. Do not edit.
from . import models

PROTOCOL_VERSION = "1.0"
MESSAGE_MODELS = {
    "SessionStartRequest": models.SessionStartRequest,
    "SessionStartResponse": models.SessionStartResponse,
    "SessionEndRequest": models.SessionEndRequest,
    "SessionEndResponse": models.SessionEndResponse,
    "ScreenState": models.ScreenState,
    "Action": models.Action,
    "EscalateRequest": models.EscalateRequest,
    "EscalateResponse": models.EscalateResponse,
    "FeedbackRequest": models.FeedbackRequest,
    "FeedbackResponse": models.FeedbackResponse,
    "ProtocolError": models.ProtocolError,
}
