# generated by datamodel-codegen:
#   filename:  protocol.schema.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    StrictBool,
    StrictFloat,
    StrictStr,
)


class SessionId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description='Opaque identifier; consumers must not infer authorization from its spelling.',
            max_length=80,
            pattern='^[A-Za-z0-9][A-Za-z0-9_-]*$',
            title='SessionId',
        ),
    ]


class TaskId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description='Opaque identifier; consumers must not infer authorization from its spelling.',
            max_length=80,
            pattern='^[A-Za-z0-9][A-Za-z0-9_-]*$',
            title='TaskId',
        ),
    ]


class DocumentId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description='Opaque identifier; consumers must not infer authorization from its spelling.',
            max_length=80,
            pattern='^[A-Za-z0-9][A-Za-z0-9_-]*$',
            title='DocumentId',
        ),
    ]


class ActionId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description='Opaque identifier; consumers must not infer authorization from its spelling.',
            max_length=80,
            pattern='^[A-Za-z0-9][A-Za-z0-9_-]*$',
            title='ActionId',
        ),
    ]


class TabId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description='Opaque identifier; consumers must not infer authorization from its spelling.',
            max_length=80,
            pattern='^[A-Za-z0-9][A-Za-z0-9_-]*$',
            title='TabId',
        ),
    ]


class CropId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description='Opaque identifier; consumers must not infer authorization from its spelling.',
            max_length=80,
            pattern='^[A-Za-z0-9][A-Za-z0-9_-]*$',
            title='CropId',
        ),
    ]


class ElementId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(max_length=80, pattern='^[ev][A-Za-z0-9_-]+$', title='ElementId'),
    ]


class ProtocolVersion(RootModel[Literal['1.0']]):
    root: Annotated[Literal['1.0'], Field(title='ProtocolVersion')]


class Mode(RootModel[Literal['ask', 'guide', 'agent', 'background']]):
    root: Annotated[Literal['ask', 'guide', 'agent', 'background'], Field(title='Mode')]


class PiiClass(
    RootModel[
        Literal[
            'secret',
            'name',
            'email',
            'phone',
            'address',
            'card',
            'bank_account',
            'aadhaar',
            'pan',
            'ifsc',
            'upi',
            'iban',
            'ip',
            'dob',
            'api_key',
            'jwt',
            'face',
            'location',
            'organization',
            'amount',
            'other',
        ]
    ]
):
    root: Annotated[
        Literal[
            'secret',
            'name',
            'email',
            'phone',
            'address',
            'card',
            'bank_account',
            'aadhaar',
            'pan',
            'ifsc',
            'upi',
            'iban',
            'ip',
            'dob',
            'api_key',
            'jwt',
            'face',
            'location',
            'organization',
            'amount',
            'other',
        ],
        Field(title='PiiClass'),
    ]


class Placeholder(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            max_length=100,
            pattern='^\\{\\{(?:[A-Z][A-Z0-9_]*_[1-9][0-9]*|SECRET|TEXT_WITHHELD)\\}\\}$',
            title='Placeholder',
        ),
    ]


class BBoxItem(RootModel[StrictFloat]):
    root: Annotated[StrictFloat, Field(ge=0.0)]


class BBox(RootModel[list[StrictFloat | BBoxItem]]):
    """
    [x, y, width, height] in CSS page coordinates; crop-region boxes use crop pixels.
    """

    root: Annotated[
        list[StrictFloat | BBoxItem],
        Field(
            description='[x, y, width, height] in CSS page coordinates; crop-region boxes use crop pixels.',
            max_length=4,
            min_length=4,
            title='BBox',
        ),
    ]


class ElementState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    disabled: StrictBool | None = None
    checked: StrictBool | None = None
    selected: StrictBool | None = None
    expanded: StrictBool | None = None
    required: StrictBool | None = None
    readonly: StrictBool | None = None
    focused: StrictBool | None = None


class DisplayElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: ElementId
    role: Annotated[StrictStr, Field(max_length=64, pattern='^[a-z][a-z0-9_-]*$')]
    name: Annotated[StrictStr, Field(max_length=4096)]
    bbox: BBox
    src: Literal['dom', 'vision', 'fused', 'server_vlm']
    conf: Annotated[StrictFloat, Field(ge=0.0, le=1.0)]
    state: ElementState | None = None
    input_type: (
        Literal[
            'text',
            'search',
            'tel',
            'url',
            'email',
            'password',
            'number',
            'date',
            'datetime-local',
            'month',
            'week',
            'time',
            'color',
            'range',
            'checkbox',
            'radio',
            'file',
            'hidden',
            'submit',
            'reset',
            'button',
            'image',
        ]
        | None
    ) = None
    landmark: Annotated[StrictStr | None, Field(max_length=128)] = None
    image: Literal['face_redacted', 'masked'] | None = None
    suspicious: StrictBool | None = None


class EmptyElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: ElementId
    role: Annotated[StrictStr, Field(max_length=64, pattern='^[a-z][a-z0-9_-]*$')]
    name: Annotated[StrictStr, Field(max_length=4096)]
    bbox: BBox
    src: Literal['dom', 'vision', 'fused', 'server_vlm']
    conf: Annotated[StrictFloat, Field(ge=0.0, le=1.0)]
    state: ElementState | None = None
    input_type: (
        Literal[
            'text',
            'search',
            'tel',
            'url',
            'email',
            'password',
            'number',
            'date',
            'datetime-local',
            'month',
            'week',
            'time',
            'color',
            'range',
            'checkbox',
            'radio',
            'file',
            'hidden',
            'submit',
            'reset',
            'button',
            'image',
        ]
        | None
    ) = None
    landmark: Annotated[StrictStr | None, Field(max_length=128)] = None
    image: Literal['face_redacted', 'masked'] | None = None
    suspicious: StrictBool | None = None
    value_state: Literal['empty']
    value: Literal['']


class FilledElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: ElementId
    role: Annotated[StrictStr, Field(max_length=64, pattern='^[a-z][a-z0-9_-]*$')]
    name: Annotated[StrictStr, Field(max_length=4096)]
    bbox: BBox
    src: Literal['dom', 'vision', 'fused', 'server_vlm']
    conf: Annotated[StrictFloat, Field(ge=0.0, le=1.0)]
    state: ElementState | None = None
    input_type: (
        Literal[
            'text',
            'search',
            'tel',
            'url',
            'email',
            'password',
            'number',
            'date',
            'datetime-local',
            'month',
            'week',
            'time',
            'color',
            'range',
            'checkbox',
            'radio',
            'file',
            'hidden',
            'submit',
            'reset',
            'button',
            'image',
        ]
        | None
    ) = None
    landmark: Annotated[StrictStr | None, Field(max_length=128)] = None
    image: Literal['face_redacted', 'masked'] | None = None
    suspicious: StrictBool | None = None
    value_state: Literal['filled']
    value: Annotated[StrictStr, Field(max_length=4096, min_length=1)]


class RedactedElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: ElementId
    role: Annotated[StrictStr, Field(max_length=64, pattern='^[a-z][a-z0-9_-]*$')]
    name: Annotated[StrictStr, Field(max_length=4096)]
    bbox: BBox
    src: Literal['dom', 'vision', 'fused', 'server_vlm']
    conf: Annotated[StrictFloat, Field(ge=0.0, le=1.0)]
    state: ElementState | None = None
    input_type: (
        Literal[
            'text',
            'search',
            'tel',
            'url',
            'email',
            'password',
            'number',
            'date',
            'datetime-local',
            'month',
            'week',
            'time',
            'color',
            'range',
            'checkbox',
            'radio',
            'file',
            'hidden',
            'submit',
            'reset',
            'button',
            'image',
        ]
        | None
    ) = None
    landmark: Annotated[StrictStr | None, Field(max_length=128)] = None
    image: Literal['face_redacted', 'masked'] | None = None
    suspicious: StrictBool | None = None
    value_state: Literal['redacted']
    value: Placeholder
    pii_class: PiiClass


class Element(
    RootModel[DisplayElement | EmptyElement | FilledElement | RedactedElement]
):
    root: Annotated[
        DisplayElement | EmptyElement | FilledElement | RedactedElement,
        Field(title='Element'),
    ]


class Viewport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    w: Annotated[int, Field(ge=1, le=100000)]
    h: Annotated[int, Field(ge=1, le=100000)]
    scroll_x: StrictFloat | None = None
    scroll_y: StrictFloat
    page_w: Annotated[int | None, Field(ge=1, le=10000000)] = None
    page_h: Annotated[int, Field(ge=1, le=10000000)]


class Page(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: Annotated[StrictStr, Field(max_length=2048, pattern='^https?://[^\\s]+$')]
    title: Annotated[StrictStr, Field(max_length=512)]
    viewport: Viewport


class ClientCapabilities(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    browser: Literal['chrome', 'firefox']
    backend: Literal['webgpu', 'wasm-simd-threads', 'wasm-simd', 'wasm', 'none']
    detectors: Annotated[
        list[Literal['dom', 'rules', 'ner', 'ocr', 'face', 'ui', 'barcode', 'script']],
        Field(max_length=8, min_length=0),
    ]
    crops: StrictBool


class AllowedDomain(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            max_length=253,
            pattern='^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$',
        ),
    ]


class SessionStartRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    task_id: TaskId
    task_version: Annotated[int, Field(ge=1, le=9007199254740991)]
    task: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    allowed_domains: Annotated[list[AllowedDomain], Field(max_length=32, min_length=1)]
    capabilities: ClientCapabilities
    mode: Mode
    voice: StrictBool | None = None
    granted_tabs: Annotated[list[TabId] | None, Field(max_length=8, min_length=0)] = (
        None
    )
    read_only: StrictBool


class SessionStartResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    session_id: SessionId
    task_id: TaskId
    task_version: Annotated[int, Field(ge=1, le=9007199254740991)]
    expires_in_seconds: Annotated[int, Field(ge=1, le=1800)]


class SessionEndRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    session_id: SessionId
    task_id: TaskId
    task_version: Annotated[int, Field(ge=1, le=9007199254740991)]
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]


class SessionEndResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    session_id: SessionId
    task_id: TaskId
    task_version: Annotated[int, Field(ge=1, le=9007199254740991)]
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    status: Literal['ended']


class ActionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action_id: ActionId
    status: Literal['ok', 'failed', 'mismatch', 'unknown']
    page_changed: StrictBool
    reason: (
        Literal[
            'target_missing',
            'target_changed',
            'stale_observation',
            'binding_denied',
            'unsupported_control',
            'expectation_failed',
            'timeout',
            'cancelled',
            'permission_denied',
            'egress_blocked',
            'execution_error',
        ]
        | None
    ) = None


class UserTurn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Literal['voice', 'text']
    text: Annotated[StrictStr, Field(max_length=4096)]
    interrupt: StrictBool


class UserInteraction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['click', 'input', 'navigate']
    target: ElementId | None = None
    after_step: ActionId


class TabDigest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tab: TabId
    title: Annotated[StrictStr, Field(max_length=512)]
    digest: Annotated[StrictStr, Field(max_length=4096)]


class TextContextItem(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=4096)]


class FullScreenState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    session_id: SessionId
    task_id: TaskId
    task_version: Annotated[int, Field(ge=1, le=9007199254740991)]
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    doc_id: DocumentId
    observation_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    step: Annotated[int, Field(ge=0, le=9007199254740991)]
    page: Page
    redaction_scheme: Literal['v1']
    mode: Mode
    elements: Annotated[list[Element], Field(max_length=300, min_length=0)]
    text_context: Annotated[list[TextContextItem], Field(max_length=100, min_length=0)]
    suspicious: StrictBool
    last_action_result: ActionResult | None = None
    user_turn: UserTurn | None = None
    user_interaction: UserInteraction | None = None
    tabs: Annotated[list[TabDigest] | None, Field(max_length=8, min_length=0)] = None
    kind: Literal['full']


class DiffScreenState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    session_id: SessionId
    task_id: TaskId
    task_version: Annotated[int, Field(ge=1, le=9007199254740991)]
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    doc_id: DocumentId
    observation_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    step: Annotated[int, Field(ge=0, le=9007199254740991)]
    page: Page
    redaction_scheme: Literal['v1']
    mode: Mode
    elements: Annotated[list[Element], Field(max_length=300, min_length=0)]
    text_context: Annotated[list[TextContextItem], Field(max_length=100, min_length=0)]
    suspicious: StrictBool
    last_action_result: ActionResult | None = None
    user_turn: UserTurn | None = None
    user_interaction: UserInteraction | None = None
    tabs: Annotated[list[TabDigest] | None, Field(max_length=8, min_length=0)] = None
    kind: Literal['diff']
    base_observation_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    removed: Annotated[list[ElementId], Field(max_length=300, min_length=0)]


class ScreenState(RootModel[FullScreenState | DiffScreenState]):
    root: Annotated[FullScreenState | DiffScreenState, Field(title='ScreenState')]


class ValueExpectation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    element: ElementId
    value_equals: Annotated[StrictStr, Field(max_length=4096)]


class AppearExpectation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    appear: ElementId


class DisappearExpectation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    disappear: ElementId


class UrlExpectation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url_equals: Annotated[
        StrictStr, Field(max_length=2048, pattern='^https?://[^\\s]+$')
    ]


class Expectation(
    RootModel[
        ValueExpectation | AppearExpectation | DisappearExpectation | UrlExpectation
    ]
):
    root: Annotated[
        ValueExpectation | AppearExpectation | DisappearExpectation | UrlExpectation,
        Field(title='Expectation'),
    ]


class ClickCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['click']
    target: ElementId


class TypeCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['type']
    target: ElementId
    text: Annotated[StrictStr, Field(max_length=4096)]
    clear_first: StrictBool


class SelectCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['select']
    target: ElementId
    option: Annotated[StrictStr, Field(max_length=4096)]


class ScrollAmountCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['scroll']
    direction: Literal['up', 'down', 'left', 'right']
    amount: Annotated[int, Field(ge=1, le=100000)]


class ScrollTargetCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['scroll']
    to_element: ElementId


class PressKeyCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['press_key']
    key: Literal['Enter', 'Tab', 'Escape']


class WaitDurationCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['wait']
    ms: Annotated[int, Field(ge=0, le=30000)]


class WaitUntilCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['wait']
    until: AppearExpectation | DisappearExpectation


class NavigateCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['navigate']
    url: Annotated[StrictStr, Field(max_length=2048, pattern='^https?://[^\\s]+$')]


class ExtractCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['extract']
    target: ElementId
    field: Literal['name', 'value', 'text_context']


class Option(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=256)]


class AskUserCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['ask_user']
    question: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    options: Annotated[list[Option] | None, Field(max_length=10, min_length=1)] = None


class EscalateCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['escalate']
    targets: Annotated[list[ElementId], Field(max_length=2, min_length=1)]
    question: Annotated[StrictStr, Field(max_length=4096, min_length=1)]


class DoneCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['done']
    summary: Annotated[StrictStr, Field(max_length=4096)]


class SpeechText(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            max_length=1000,
            pattern='^\\s*(?:\\S+\\s+){0,24}\\S+\\s*$',
            title='SpeechText',
        ),
    ]


class PointCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['point']
    target: ElementId
    say: SpeechText
    style: Literal['pointer', 'circle', 'spotlight']
    advance_on: Literal['click', 'input', 'navigate']


class Annotation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['circle', 'arrow', 'badge', 'label', 'spotlight']
    target: ElementId
    label: Annotated[StrictStr | None, Field(max_length=256)] = None


class AnnotateCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['annotate']
    shapes: Annotated[list[Annotation], Field(max_length=30, min_length=1)]
    say: SpeechText


class SayCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['say']
    text: SpeechText


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tab: TabId
    doc_id: DocumentId
    element: ElementId | None = None


class AnswerCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['answer']
    text: Annotated[StrictStr, Field(max_length=8192)]
    citations: Annotated[list[Citation], Field(max_length=30, min_length=0)]


class SwitchTabCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['switch_tab']
    tab: TabId


class Item(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(max_length=4096)]


class ReportCommand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['report']
    summary: Annotated[StrictStr, Field(max_length=4096)]
    items: Annotated[list[Item], Field(max_length=100, min_length=0)]


class ActionCommand(
    RootModel[
        ClickCommand
        | TypeCommand
        | SelectCommand
        | ScrollAmountCommand
        | ScrollTargetCommand
        | PressKeyCommand
        | WaitDurationCommand
        | WaitUntilCommand
        | NavigateCommand
        | ExtractCommand
        | AskUserCommand
        | EscalateCommand
        | DoneCommand
        | PointCommand
        | AnnotateCommand
        | SayCommand
        | AnswerCommand
        | SwitchTabCommand
        | ReportCommand
    ]
):
    root: Annotated[
        ClickCommand
        | TypeCommand
        | SelectCommand
        | ScrollAmountCommand
        | ScrollTargetCommand
        | PressKeyCommand
        | WaitDurationCommand
        | WaitUntilCommand
        | NavigateCommand
        | ExtractCommand
        | AskUserCommand
        | EscalateCommand
        | DoneCommand
        | PointCommand
        | AnnotateCommand
        | SayCommand
        | AnswerCommand
        | SwitchTabCommand
        | ReportCommand,
        Field(title='ActionCommand'),
    ]


class Progress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    step: Annotated[int, Field(ge=0, le=9007199254740991)]
    subgoal: Annotated[StrictStr, Field(max_length=512)]
    remaining_estimate: Annotated[int, Field(ge=0, le=10000)]


class Action(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    session_id: SessionId
    task_id: TaskId
    task_version: Annotated[int, Field(ge=1, le=9007199254740991)]
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    doc_id: DocumentId
    observation_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    action_id: ActionId
    action: ActionCommand
    expect: Expectation | None = None
    consequential: StrictBool
    risk: Literal['low', 'medium', 'high']
    thought: Annotated[StrictStr | None, Field(max_length=1024)] = None
    progress: Progress | None = None


class CropRegion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bbox: BBox
    content_class: Literal[
        'ui_chrome',
        'known_icon',
        'supported_text',
        'chart',
        'face',
        'avatar',
        'photo',
        'video',
        'document_image',
        'handwriting',
        'map',
        'barcode',
        'unsupported_text',
        'unclassified',
    ]
    masked: StrictBool
    checks: Annotated[
        list[
            Literal[
                'ui',
                'icon',
                'ocr',
                'rules',
                'ner',
                'face',
                'barcode',
                'script',
                'policy',
            ]
        ],
        Field(max_length=9, min_length=0),
    ]


class RedactedCrop(BaseModel):
    """
    Only fully redacted crops are eligible. D-11/D-14 must verify decoded dimensions, coverage, masks and content; this schema cannot prove image safety.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    crop_id: CropId
    target: ElementId
    bbox: BBox
    width: Annotated[int, Field(ge=1, le=512)]
    height: Annotated[int, Field(ge=1, le=512)]
    media_type: Literal['image/jpeg']
    data_base64: Annotated[
        StrictStr,
        Field(
            max_length=1048576,
            min_length=4,
            pattern='^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$',
        ),
    ]
    regions: Annotated[list[CropRegion], Field(max_length=1000, min_length=1)]


class EscalateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    session_id: SessionId
    task_id: TaskId
    task_version: Annotated[int, Field(ge=1, le=9007199254740991)]
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    doc_id: DocumentId
    observation_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    question: Annotated[StrictStr, Field(max_length=4096, min_length=1)]
    redaction_scheme: Literal['v1']
    crops: Annotated[list[RedactedCrop], Field(max_length=2, min_length=1)]


class VisualInterpretation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    element_id: ElementId
    role: Annotated[StrictStr, Field(max_length=64, pattern='^[a-z][a-z0-9_-]*$')]
    label: Annotated[StrictStr, Field(max_length=4096)]
    state: ElementState
    confidence: Annotated[StrictFloat, Field(ge=0.0, le=1.0)]
    src: Literal['server_vlm']


class EscalateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    session_id: SessionId
    task_id: TaskId
    task_version: Annotated[int, Field(ge=1, le=9007199254740991)]
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    doc_id: DocumentId
    observation_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    interpretations: Annotated[
        list[VisualInterpretation], Field(max_length=2, min_length=1)
    ]


class FeedbackRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    session_id: SessionId
    task_id: TaskId
    task_version: Annotated[int, Field(ge=1, le=9007199254740991)]
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    doc_id: DocumentId
    observation_id: Annotated[int, Field(ge=1, le=9007199254740991)]
    result: ActionResult


class FeedbackResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    session_id: SessionId
    task_id: TaskId
    task_version: Annotated[int, Field(ge=1, le=9007199254740991)]
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]
    status: Literal['accepted']


class ProtocolError(BaseModel):
    """
    Errors before session creation omit session correlation fields. Include known correlation fields for established sessions.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: ProtocolVersion
    session_id: SessionId | None = None
    task_id: TaskId | None = None
    task_version: Annotated[int | None, Field(ge=1, le=9007199254740991)] = None
    seq: Annotated[int | None, Field(ge=1, le=9007199254740991)] = None
    code: Literal[
        'resync_required',
        'invalid_request',
        'unsupported_version',
        'session_expired',
        'unauthorized',
        'rate_limited',
        'unavailable',
    ]
    retryable: StrictBool


class WireMessage(
    RootModel[
        SessionStartRequest
        | SessionStartResponse
        | SessionEndRequest
        | SessionEndResponse
        | ScreenState
        | Action
        | EscalateRequest
        | EscalateResponse
        | FeedbackRequest
        | FeedbackResponse
        | ProtocolError
    ]
):
    root: Annotated[
        SessionStartRequest
        | SessionStartResponse
        | SessionEndRequest
        | SessionEndResponse
        | ScreenState
        | Action
        | EscalateRequest
        | EscalateResponse
        | FeedbackRequest
        | FeedbackResponse
        | ProtocolError,
        Field(
            description='E-01 wire contract. All strings derived from a task or page require local sanitization before egress. Structural validation is not egress authorization.',
            title='WireMessage',
        ),
    ]
