"""Generate the deterministic ONNX test model used by C-02.

The model is intentionally trivial: ``Y = A * X + B`` over a 1x4 float32
tensor, with ``A`` and ``B`` baked in as initializers. That makes the expected
output checkable by hand, keeps the file a few hundred bytes, and needs no GPU
or production weights to prove that the runtime loaded, compiled and executed a
graph.

It exists so C-02 can verify real execution and backend fallback without
pulling in a production detector. Model-specific pre/post-processing and real
detectors belong to later C-lane features; production model storage is A-13.

Run from the repository root:

    uv run --locked python tools/generate-test-model.py
"""

from __future__ import annotations

from pathlib import Path

import onnx
from onnx import TensorProto, helper, numpy_helper
import numpy as np

# Kept in lockstep with EXPECTED_* in the TypeScript tests. Changing either
# side alone makes the runtime tests assert against a model that no longer
# produces those numbers.
SCALE = np.array([2.0, 2.0, 2.0, 2.0], dtype=np.float32)
OFFSET = np.array([1.0, 2.0, 3.0, 4.0], dtype=np.float32)

OUTPUT_PATH = Path("packages/extension/src/worker/runtime/testdata/linear.onnx")

# Opset 13 is old enough to be supported everywhere ONNX Runtime Web runs, and
# new enough that Mul/Add have their current broadcasting semantics.
OPSET_VERSION = 13

# Pinned deliberately. The `onnx` package defaults to its own newest IR version
# (14 at the time of writing), which ONNX Runtime Web rejects outright with
# "Unsupported model IR version" — every backend then fails to initialize and
# the failure looks like a runtime problem rather than a model problem. IR 9 is
# understood by every ORT build we target and is ample for a two-node graph.
IR_VERSION = 9


def build_model() -> onnx.ModelProto:
    """Builds ``Y = A * X + B`` as a two-node graph."""
    scale = numpy_helper.from_array(SCALE, name="scale")
    offset = numpy_helper.from_array(OFFSET, name="offset")

    x = helper.make_tensor_value_info("input", TensorProto.FLOAT, [1, 4])
    y = helper.make_tensor_value_info("output", TensorProto.FLOAT, [1, 4])

    graph = helper.make_graph(
        nodes=[
            helper.make_node("Mul", ["input", "scale"], ["scaled"], name="scale_input"),
            helper.make_node("Add", ["scaled", "offset"], ["output"], name="add_offset"),
        ],
        name="privacagent_linear_test",
        inputs=[x],
        outputs=[y],
        initializer=[scale, offset],
    )

    model = helper.make_model(
        graph,
        producer_name="privacagent/tools/generate-test-model.py",
        opset_imports=[helper.make_opsetid("", OPSET_VERSION)],
    )
    model.ir_version = IR_VERSION
    model.doc_string = (
        "Deterministic C-02 runtime test model. Y = A * X + B. "
        "Generated by tools/generate-test-model.py; same licence as this repository."
    )
    onnx.checker.check_model(model)
    return model


def main() -> None:
    model = build_model()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_bytes(model.SerializeToString())

    probe = np.array([[1.0, 2.0, 3.0, 4.0]], dtype=np.float32)
    expected = probe * SCALE + OFFSET
    print(f"wrote {OUTPUT_PATH} ({OUTPUT_PATH.stat().st_size} bytes)")
    print(f"probe   {probe.tolist()}")
    print(f"expected {expected.tolist()}")


if __name__ == "__main__":
    main()
